color: null
fieldLayouts:
  3bca9049-77d4-467f-8f5b-112c64121831:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: be201a44-98eb-4976-8f62-a29c81163c78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5df28b39-bbb0-4570-afef-5054ff1fa042
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff2af323-a5b2-4ef8-9bc2-9f110102098e
        userCondition: null
handle: asset
hasTitleField: true
icon: ''
name: Asset
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
