color: fuchsia
fieldLayouts:
  3bca9049-77d4-467f-8f5b-112c64121831:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-05T19:34:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: be201a44-98eb-4976-8f62-a29c81163c78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T19:34:32+00:00'
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5df28b39-bbb0-4570-afef-5054ff1fa042
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T19:36:43+00:00'
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: assetMobile
            includeInCards: false
            instructions: 'Display a different asset on smaller screen sizes.'
            label: 'Mobile Asset'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14fe5258-3e30-4737-adf0-1a4c5490f897
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff2af323-a5b2-4ef8-9bc2-9f110102098e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-05T19:34:32+00:00'
            elementCondition: null
            fieldUid: 929dd815-3f39-4a7a-a039-6c7ac68799b5 # Overlay
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09c408db-1227-4d55-81e3-341113cd495d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T19:34:32+00:00'
            elementCondition: null
            fieldUid: 8f0d2001-1c75-4b9a-8e74-b7e48dbc58bf # Loop Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9f9ae0c-022e-43b1-ac31-bdbee2345b55
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: ee150f7e-4f7a-48b3-bece-7f757fbc426c
        userCondition: null
handle: asset
hasTitleField: false
icon: images
name: Asset
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
