color: indigo
fieldLayouts:
  987bdd18-1e0a-4773-99c6-66ab03c6f47a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 885f9a43-56f7-4930-bc90-ddd3fa596290
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a500d511-5b23-4b2b-abce-4a581d7efb09
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae97b4e4-7938-4735-b734-84f98ec34af2 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a655456-57d9-47f3-84d2-1e3bf849b898
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aadba03-8834-4717-9dfb-74acb82be1f0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65bdc0d7-5ba4-49c3-8ce5-bb189ab237f5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bda53640-24b3-44f4-8c8b-ee991f1addba # Text Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce402ebc-0c2b-47e2-b104-d9f77f72bad6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4986ae78-9ffa-41e9-ab3b-91e866576fd5 # Max Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a569af7d-86b0-4bf9-b486-7dccab644a29
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 77748fc0-4bd8-4a5b-956e-0ce0d7263cc5
        userCondition: null
handle: banner
hasTitleField: false
icon: flag-pennant
name: Banner
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
