color: rose
fieldLayouts:
  61fd2911-eb5e-498c-8a0c-fa474cf6347a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-08T02:03:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e80af89-1db2-4634-9450-8e15448ebd1a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-27T21:13:52+00:00'
            elementCondition: null
            fieldUid: a8f5f4f5-00ed-4701-a12b-eda576eb0326 # Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05059d62-e413-42b7-bafc-02546029c18a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T02:03:44+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f64da18-3d2f-419a-bc2a-9f3f699cd2fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T02:05:00+00:00'
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: pressImage
            includeInCards: false
            instructions: null
            label: 'Blog Cover Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02e9e313-a5c1-4c8b-bc5a-d2b9d1149002
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cdb7001b-189b-4e00-863a-68f80bae0e8f
        userCondition: null
handle: blog
hasTitleField: true
icon: rss
name: Blog
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
