color: null
fieldLayouts:
  96460d80-e1d9-419c-9c2d-7329e4bda218:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a7225539-898e-4815-bb24-10d3df8bd34d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b7977904-1581-4bf1-a440-242e4c34840a # Button Label
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17b60cc2-60cf-466c-89c0-841caf8816a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a4ca78e-efcf-4c8c-81c1-2464038d63b8 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0896e96c-ba00-4383-8db3-4939ac5e321c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 31f76bc5-7752-4029-b740-d90649b0dce1
        userCondition: null
handle: button
hasTitleField: false
icon: null
name: Button
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{buttonLabel}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
