color: orange
fieldLayouts:
  fb015538-9606-4dd6-babc-e18151ad252c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7c22dc57-31b0-46d4-85c7-c3c9bab08d06
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae97b4e4-7938-4735-b734-84f98ec34af2 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bef99f18-f8ea-4bd2-9746-af92c3e1ef35
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c8f7b99d-7375-4dff-991d-9dc778fdf35d
        userCondition: null
handle: buttons
hasTitleField: false
icon: circle-dot
name: Buttons
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
