color: null
fieldLayouts:
  df86e976-74ee-4e6a-87ef-b81d9ba7e9b3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-08T21:05:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5fdc57c0-55e1-4736-b111-f34a399f270e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T05:08:52+00:00'
            elementCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 493d557f-c28f-433d-aaab-da968138949a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T21:05:02+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0f656d0-b5be-4ed1-9e07-e1e0d9c6b76a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T17:52:19+00:00'
            elementCondition: null
            fieldUid: ae97b4e4-7938-4735-b734-84f98ec34af2 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84f1c582-142f-4c4c-b955-f28d412a3c7c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d411dded-f118-468e-b95c-f68ee5dde2d9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-19T23:36:53+00:00'
            elementCondition: null
            fieldUid: 4a61545b-26f4-4008-8c2f-eb15c898b03f # Margin Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf56f9d8-677b-438b-9955-f2c1c1fb35f0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T23:36:53+00:00'
            elementCondition: null
            fieldUid: f4540b83-421e-4a47-b91d-c09c70b4e12a # Margin Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 248d9bff-c9f9-4050-93ab-d7ed29dc3cb2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T05:50:06+00:00'
            elementCondition: null
            fieldUid: 4986ae78-9ffa-41e9-ab3b-91e866576fd5 # Max Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9295d136-9561-4f9f-95b8-369f5b5073cd
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 0cbb1a0c-75b5-45c9-90e2-1bf0f588f888
        userCondition: null
handle: company
hasTitleField: false
icon: ''
name: Company
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Company
titleTranslationKeyFormat: null
titleTranslationMethod: site
