color: null
fieldLayouts:
  7c9a9ac0-f3ee-4626-bd42-59c125a4b23d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-21T21:46:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b4f668c2-2ab2-48cf-a3ba-00a1b0b381cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T21:51:13+00:00'
            elementCondition: null
            fieldUid: 022ea0cc-0378-4208-8aa9-5d66cc4e3e20 # Content Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d4bb6f1-8d58-465a-b947-75c3f3903531
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c82b7e9-2b93-4921-856e-ca3ac306c342
        userCondition: null
handle: contentBlocks
hasTitleField: false
icon: ''
name: 'Content Blocks'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
