color: null
fieldLayouts:
  f0c930c8-caae-4d94-9a4d-ce8952a50952:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7d1fc154-11ae-4a01-bf79-b32398a014df
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c15bd4b-4238-434f-b3a9-9655b8ade092
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e673e1d7-05a8-4eb2-bae4-bb60b18816e0
        userCondition: null
handle: contact
hasTitleField: true
icon: ''
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
