color: sky
fieldLayouts:
  dfcb504a-408a-4635-bc46-da2a9a4a274f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 40351363-f7af-4bad-924a-a38f80751251
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: position
            includeInCards: false
            instructions: null
            label: Position
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d18a0177-59d7-4b25-be48-f3f6c3f5458f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77cbce15-f8f2-447c-9110-cb36d641174d # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 750ea2e7-f40c-42de-a4d2-a1e7f8a8131d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ec55fb3-93d6-4367-9e44-53b7057e7e7c
        userCondition: null
handle: employee
hasTitleField: true
icon: user-helmet-safety
name: Employee
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
