color: null
fieldLayouts:
  0ffa2798-4acb-406d-84c4-e72c592c7e08:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7c0946b2-b1a9-4274-a5e0-82ab7ef71630
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c962d78-ae5d-46be-9d3e-8c3869dff3ce # Featured Project
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d85926a3-d127-420c-9d8f-32ecb27fd33a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6768cf1c-b340-494b-8c86-366ccff94e5f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae97b4e4-7938-4735-b734-84f98ec34af2 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7475cd3-b9dc-4608-b279-ee2ba2a5cb90
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c43e04ab-eae2-4536-b580-06e667e61fac
        userCondition: null
handle: featuredProject
hasTitleField: false
icon: ''
name: 'Featured Project'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
