color: red
fieldLayouts:
  c2f35092-fa59-4bca-a5b9-d6d6148dd85b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9c63cec4-8241-4b95-8b54-cb450f522e9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c962d78-ae5d-46be-9d3e-8c3869dff3ce # Featured Project
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14181a23-3f91-4121-80bd-0ed795d54d09
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: text
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd8c6444-55f1-4437-9ae9-67f4b9b8b0c5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ae97b4e4-7938-4735-b734-84f98ec34af2 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47ecb100-eddd-42d4-b1af-97d9d86d64a7
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 1e219b3b-fab9-4841-afae-fe43fee5b156
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bda53640-24b3-44f4-8c8b-ee991f1addba # Text Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0783ad6f-b361-45fb-af04-f7743610dc22
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4986ae78-9ffa-41e9-ab3b-91e866576fd5 # Max Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5da323f7-24a6-4cee-b338-d90c160ff72b
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 54cf1a9c-133c-4034-8794-53619b16bc02
        userCondition: null
handle: featuredProject
hasTitleField: true
icon: star
name: 'Featured Project'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
