color: yellow
fieldLayouts:
  fa07811d-05d3-4b05-879b-b1b0cef520ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-07T22:04:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e37ee6e4-e180-470e-84bd-0c1932f9a139
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T22:04:00+00:00'
            elementCondition: null
            fieldUid: a8f5f4f5-00ed-4701-a12b-eda576eb0326 # Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18248915-19f7-4cbd-bc29-5018e271caaf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T22:04:00+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27fa231a-15ce-4e39-bec2-7be71f59884a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-08T02:03:45+00:00'
            elementCondition: null
            fieldUid: f150ae50-f438-4d0a-97d8-ca26506a57dc # Magazine File
            handle: pressImage
            includeInCards: false
            instructions: null
            label: 'Magazine Cover Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6ce9f94-66a0-491b-a4b1-67a7c81c8ddf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T22:05:10+00:00'
            elementCondition: null
            fieldUid: f150ae50-f438-4d0a-97d8-ca26506a57dc # Magazine File
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0bc19af5-b4bd-491d-ac31-75e80a45b378
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df689217-6255-4a2b-964a-82da2cf9cdab
        userCondition: null
handle: magazine
hasTitleField: true
icon: book
name: Magazine
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
