color: null
fieldLayouts:
  7c5fac26-2ac1-457c-a4dd-82fb8658c839:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ca2f7903-5643-426d-8d81-9d58eb398cdd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e4b4add-061e-4eab-92df-597242f18a90 # Primary Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1066f722-7a20-4939-82fb-7ef4df3fc225
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4f214814-db96-4951-a3b1-03392ef7ef4d # Entries
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8b23d78-34b5-4a87-acc2-9a1eb732da86
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ddebfd1-5036-4a07-b37b-f05454d73c60
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6bfc4dee-2b41-4e20-aba0-17401cd742e8
        userCondition: null
handle: navigation
hasTitleField: true
icon: null
name: Navigation
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
