color: orange
fieldLayouts:
  1df27aef-3e2f-41a2-88dc-f257d1215083:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 467843e7-afda-4f9c-a548-664e67d1e2b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: null
            includeInCards: false
            instructions: null
            label: Position
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c598f3ba-76bf-402a-82bb-372733724888
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77cbce15-f8f2-447c-9110-cb36d641174d # Image
            handle: null
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2c44764-804d-4b69-a03d-0a41c950cde4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8fb86bb4-783f-488e-97b7-0b359457932a
        userCondition: null
handle: partner
hasTitleField: true
icon: user
name: Partner
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
