color: red
fieldLayouts:
  25a76be6-e271-4d74-a09b-901516e38a61:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 446b6ac8-d66e-4c16-96ac-b8b3d9d8d028
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b1fa7753-aeec-4bb1-b26f-e1dd50f6b441
        userCondition: null
handle: projectCategory
hasTitleField: true
icon: list
name: 'Project Category'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
