color: null
fieldLayouts:
  b68ae164-c29f-4a5e-a83a-61a4da8bf4f6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 981c0f3c-3269-4c6e-9d6f-e639bd0bf1f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: newBuildsText
            includeInCards: false
            instructions: null
            label: 'New Builds Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 817cf32b-e4db-4908-be2c-608d5edd5199
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15f01c47-3842-4ce9-9ab5-b6757399910b # New Builds Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c00efcde-8555-437e-913f-f3a5a9eb4385
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: remodelsText
            includeInCards: false
            instructions: null
            label: 'Remodels Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f6b28c0-0d5f-43a5-aa03-7d74b098e3bb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4d89015-cc42-4dfe-9b5d-4709925e659f # Remodels Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72a50a07-244b-4281-a64d-77e0276752b4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e4c194a1-ec7b-48c4-ac57-b083ab42e821
        userCondition: null
handle: projects
hasTitleField: false
icon: null
name: Projects
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Projects
titleTranslationKeyFormat: null
titleTranslationMethod: site
