color: emerald
fieldLayouts:
  080afdf9-c1b4-4d82-a2d6-d9ed43641a85:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c3cac62b-64e9-490b-aae0-b16a41935a89
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b9cd007-b263-4d95-821d-014590cc1f0f # Project Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63e1ba10-d3f4-418f-be56-8c3af860dc4d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e18f1d5-2eaa-4991-92ac-5b50d48d27c7 # Location
            handle: projectLocation
            includeInCards: false
            instructions: null
            label: 'Project Location'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d261a74e-9c87-4341-968c-56bd8f3cdcd7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8f5f4f5-00ed-4701-a12b-eda576eb0326 # Date
            handle: projectDate
            includeInCards: false
            instructions: null
            label: 'Project Date'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73212fa1-675d-4864-8784-a9d90a8d3d70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d1719d0-caff-4e5a-8f9c-6a29d3d7d336
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b74708b-0a74-4152-ace3-2ead102d9b45
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: projectDescription
            includeInCards: false
            instructions: null
            label: 'Project Description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e17caca1-3b3d-498a-ab16-a2a3d2ee75a7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b20b8a1-5716-4585-9132-dd9450af92b6
        userCondition: null
handle: project
hasTitleField: true
icon: house
name: Project
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
