color: null
fieldLayouts:
  a4f13285-ed14-44a6-af74-2478bd72c71c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-08T00:18:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a6396540-21f4-4095-ba2d-e3a9d5aff31f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T00:24:00+00:00'
            elementCondition: null
            fieldUid: 1cc8dda7-e3e2-4988-abfd-d613509a99cd # Image
            handle: slideImage
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 456b7fde-1642-45a0-b85f-ace54a724f30
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T00:24:00+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8085fcfa-8e71-4bff-8880-643e4a50ada8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f5732404-50d2-4adb-a1a8-b5e49787be97
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-08T00:21:27+00:00'
            elementCondition: null
            fieldUid: f6704256-c578-402a-ab33-5ac9687059bb # Height
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fb55bec-3152-401e-bbfb-64f202714cf2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T00:21:27+00:00'
            elementCondition: null
            fieldUid: 8a78e2ab-5ef3-4b0b-8141-22b9b95d4928 # Visible Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3572e404-d995-4601-8885-30eb7612ccc2
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: a5a8e8ec-1574-4d7c-a54a-ab4b7f8ffb4d
        userCondition: null
handle: slide
hasTitleField: true
icon: ''
name: Slide
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
