color: null
fieldLayouts:
  679a1860-4797-4cca-a899-0dbd3621b37e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-20T00:05:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f5cf5234-aa86-43e8-a6b7-1e14d59c59b3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T00:05:54+00:00'
            elementCondition: null
            fieldUid: ea3fb6de-e06e-4078-a66e-62058977442f # Landing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3e93f43-766b-48f3-a974-73d91b1257dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T05:59:17+00:00'
            elementCondition: null
            heading: Introduction
            type: craft\fieldlayoutelements\Heading
            uid: ef7005fa-f2c9-42f4-b947-027a7cc54d54
            userCondition: null
          -
            dateAdded: '2024-08-20T00:41:33+00:00'
            elementCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e43212d-8e06-4ea1-97e4-ec5403446297
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T00:36:54+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 361c7c03-beea-405c-bbbf-6f36ddfb2c3e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T05:04:58+00:00'
            elementCondition: null
            fieldUid: ae97b4e4-7938-4735-b734-84f98ec34af2 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efa17461-ea90-4d59-aaa5-318a86a57ed0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-23T05:22:24+00:00'
            elementCondition: null
            heading: 'Bottom Banner'
            type: craft\fieldlayoutelements\Heading
            uid: d17cc541-7348-49b2-9ec5-e8ab81d2be2b
            userCondition: null
          -
            dateAdded: '2024-08-22T06:00:33+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: bannerText
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 719a0a7a-9944-40bc-8a5c-6791a30e142b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T06:00:33+00:00'
            elementCondition: null
            fieldUid: b7977904-1581-4bf1-a440-242e4c34840a # Button Label
            handle: bannerLabel
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ac91c34-ff72-4d54-bfe2-db9b60723ec8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-22T06:00:33+00:00'
            elementCondition: null
            fieldUid: 26fa7b55-e9e5-4fbb-a5e1-0cc31f223c1e # Button Link
            handle: bannerLink
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d80ae53a-9c97-425d-8dfa-88b8234c4597
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 864a130e-644b-4264-9ac7-d547c861ffa2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-20T00:46:28+00:00'
            elementCondition: null
            fieldUid: 4a61545b-26f4-4008-8c2f-eb15c898b03f # Margin Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6eb69b47-128c-4ea0-840b-178a970f3c06
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T00:46:28+00:00'
            elementCondition: null
            fieldUid: f4540b83-421e-4a47-b91d-c09c70b4e12a # Margin Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18186344-9be9-4589-8216-244706c870f2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-23T05:29:33+00:00'
            elementCondition: null
            fieldUid: 4986ae78-9ffa-41e9-ab3b-91e866576fd5 # Max Width
            handle: topMaxWidth
            includeInCards: false
            instructions: null
            label: 'Top Text Max Width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb120511-f6c9-4332-845b-979ac4cf67a9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-23T05:16:50+00:00'
            elementCondition: null
            fieldUid: 4986ae78-9ffa-41e9-ab3b-91e866576fd5 # Max Width
            handle: bottomMaxWidth
            includeInCards: false
            instructions: null
            label: 'Bottom Banner Max Width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: befdc8c6-1930-4269-a468-5c35cfed88c0
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: a28bf416-fdf9-4f74-96a3-505687765a1c
        userCondition: null
handle: story
hasTitleField: false
icon: ''
name: Story
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Story
titleTranslationKeyFormat: null
titleTranslationMethod: site
