color: purple
fieldLayouts:
  ba43b666-4d65-471c-9733-7507f429550a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-08T02:03:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a4a6b920-f2e4-4a4c-a0e0-c7263225ae80
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T02:03:02+00:00'
            elementCondition: null
            fieldUid: 5a4ca78e-efcf-4c8c-81c1-2464038d63b8 # Button Link
            handle: websiteLink
            includeInCards: false
            instructions: null
            label: 'Website Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d84e563-3ef0-44d3-ba0f-c6f602708796
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-26T22:49:04+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d17a1e8a-f592-4ac6-9e7c-a82c40c6d5e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T02:04:06+00:00'
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: pressImage
            includeInCards: false
            instructions: null
            label: 'Website Cover Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b7816a3-2ed2-4cb0-9f71-c67c890e5c2a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c408340-ea81-40b9-8cac-75a3607c59d0
        userCondition: null
handle: website
hasTitleField: true
icon: browser
name: Website
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
