altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  950b8908-409a-4440-a43a-c709b91acfb0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c670e187-5b8f-4104-a774-20acad72e442
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 84daa1b8-8282-497c-bf8a-761987908f2d
        userCondition: null
fs: uploads
handle: general
name: General
sortOrder: 9
subpath: general
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
