altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f498705a-dcf1-4b2f-b02c-bbf013770c70:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ebaca9c6-4c4d-4e3e-8705-10566365e342
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 762e4c6d-0174-4c8b-9c9b-61b643db085d
        userCondition: null
fs: uploads
handle: magazines
name: Magazines
sortOrder: 8
subpath: magazines
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
