altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  6c3a88b5-577b-4a95-bfd5-8215f3de0528:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c09bf880-c935-4613-a747-45e18510d882
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 49f5f884-f378-4961-8150-3242886bb2f1
        userCondition: null
fs: uploads
handle: offices
name: Offices
sortOrder: 7
subpath: offices
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
