altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f12a87de-05f8-4dc6-8511-f05908be3ad7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6de2bef8-ebaf-4f23-8814-dbb685e3a7ff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0a48817d-8e61-4b31-bdc9-1c7253f72d16
        userCondition: null
fs: uploads
handle: press
name: Press
sortOrder: 6
subpath: press
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
