columnSuffix: null
handle: banner
instructions: null
name: Banner
searchable: false
settings:
  createButtonLabel: 'New Banner'
  entryTypes:
    - 84b49fbd-67b9-4021-9790-4d862971a1fb # Text
    - 98531642-0cb8-4a38-a70c-ddd5f537d751 # Buttons
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
