columnSuffix: null
handle: buttonLabel
instructions: null
name: 'Button Label'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: Button
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
