columnSuffix: null
handle: colorScheme
instructions: null
name: 'Color Scheme'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Red
        -
          - value
          - red
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - white
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
