columnSuffix: null
handle: featuredProject
instructions: 'Choose several projects to display on the home page. One of the selected projects will randomly display each time the home page is loaded.'
name: 'Featured Project'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 4
  minRelations: null
  selectionLabel: 'Add a Project'
  showCardsInGrid: true
  showSiteMenu: true
  sources:
    - 'section:d7bc45f1-f1c6-4fe7-aad5-a83242f68d4c' # Projects
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
