columnSuffix: null
handle: featuredProjects
instructions: null
name: 'Featured Projects'
searchable: false
settings:
  createButtonLabel: 'New Featured Project Block'
  entryTypes:
    - 94cb9947-273b-4b08-994c-6ef6402b164b # Featured Project
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
