columnSuffix: null
handle: Location
instructions: null
name: Location
searchable: false
settings:
  maxAddresses: 1
  minAddresses: null
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
