columnSuffix: null
handle: loopVideo
instructions: null
name: 'Loop Video'
searchable: false
settings:
  default: true
  offLabel: 'No Loop'
  onLabel: Loop
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
