columnSuffix: null
handle: magazineFile
instructions: null
name: 'Magazine File'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
    - pdf
    - video
  branchLimit: null
  defaultUploadLocationSource: 'volume:e1c930be-4e19-4db0-ad0a-3c422934e22c' # Magazines
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:0df67807-28de-4196-83d0-7659095a96c0' # Projects
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:e1c930be-4e19-4db0-ad0a-3c422934e22c' # Magazines
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
