columnSuffix: null
handle: newBuildsButton
instructions: null
name: 'New Builds Button'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 2a474d4a-c4ce-4af9-8df0-20b69b317f1c # Button
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
