columnSuffix: null
handle: office
instructions: null
name: Office
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Jackson Office'
        -
          - value
          - jacksonOffice
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Driggs Office'
        -
          - value
          - driggsOffice
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Remote
        -
          - value
          - remote
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
