columnSuffix: null
handle: overlay
instructions: 'Choose a number from 0 to 10 for overlay opacity.'
name: Overlay
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 10
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
