columnSuffix: null
handle: tetonLocation
instructions: null
name: 'Teton Valley Location'
searchable: false
settings:
  maxAddresses: 1
  minAddresses: null
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
