columnSuffix: null
handle: textAlignment
instructions: null
name: 'Text Alignment'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Top Left'
        -
          - value
          - topLeft
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Top Center'
        -
          - value
          - topCenter
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Top Right'
        -
          - value
          - topRight
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Center Left'
        -
          - value
          - centerLeft
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Center Right'
        -
          - value
          - centerRight
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Bottom Left'
        -
          - value
          - bottomLeft
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Bottom Center'
        -
          - value
          - bottomCenter
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Bottom Right'
        -
          - value
          - bottomRight
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
