columnSuffix: null
handle: visibleCards
instructions: 'Choose how many cards in the slider will be on the screen at one time.'
name: 'Visible Cards'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '1'
        -
          - value
          - '1'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2'
        -
          - value
          - '2'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3'
        -
          - value
          - '3'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '4'
        -
          - value
          - '4'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
