defaultPlacement: end
enableVersioning: true
entryTypes:
  - a29a748c-48f5-4036-80ab-2ac52e338956 # Footer
handle: footer
maxAuthors: 1
name: Footer
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # JH Builders
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
