defaultPlacement: end
enableVersioning: true
entryTypes:
  - 94cb9947-273b-4b08-994c-6ef6402b164b # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # JH Builders
    enabledByDefault: true
    hasUrls: true
    template: _pages/home
    uriFormat: __home__
type: single
