defaultPlacement: end
enableVersioning: true
entryTypes:
  - 86453256-3536-4893-8b3e-621ab30831dd # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # JH Builders
    enabledByDefault: true
    hasUrls: true
    template: _pages/home.twig
    uriFormat: __home__
type: single
