defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8b433bb6-cab9-45f3-bac0-0eecc02c1cd0 # Navigation
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # JH Builders
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
