defaultPlacement: end
enableVersioning: true
entryTypes:
  - 88e330b5-199c-4dee-a8f3-d5f391f8df20 # Magazine
  - 9c2b25c2-13cb-44cf-8e74-612cb1025c01 # Website
  - a777c431-cdb1-4b6a-bb15-4ae76fbaf9a4 # Blog
handle: press
maxAuthors: 1
name: Press
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # JH Builders
    enabledByDefault: true
    hasUrls: true
    template: _pages/press
    uriFormat: 'company/{slug}'
structure:
  maxLevels: null
  uid: 5a73b1e3-c993-468c-ac71-b272cdbd956e
type: structure
