defaultPlacement: beginning
enableVersioning: true
entryTypes:
  - fc6ef365-7b24-4504-a826-07dae12b991c # Employee
  - 08212732-97cb-4fe1-80d5-22da0da1d83a # Partner
handle: staff
maxAuthors: 1
name: Staff
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # JH Builders
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: 387bc4cc-0ee2-4341-8117-e3dcbf301d56
type: structure
