defaultPlacement: end
enableVersioning: true
entryTypes:
  - b41a2277-6577-4a6a-85b1-34d09f682df9 # Story
handle: story
maxAuthors: 1
name: Story
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # JH Builders
    enabledByDefault: true
    hasUrls: true
    template: _pages/story
    uriFormat: story
type: single
