handle: careerForm
name: 'Career Form'
outputCssLayout: true
outputCssLocation: page-header
outputCssTheme: true
outputJsBase: true
outputJsLocation: page-footer
outputJsTheme: true
sortOrder: 1
template: _includes/_form
useCustomTemplates: true
